### ISSUE TITLE
Acking/nacking when resolveLinktos is enabled

### ISSUE THREAD

**Issue by sebastianseilund** [tbug/elixir-eventstore-http-client#1]
When `resolveLinktos` is enabled for a subscription, the returned `eventId` from `GET /subscriptions/:stream/:group` is not the id you can use to ack/nack messages with. It will be the `eventId` of the original event, but Event Store expects you to ack/nack using the ID of  the event that's actually on the stream (the linkTo-event).

The only other way I've found to solve that is to use the `relation=ack` or `relation=nack` `links` from the received event. I guess you could store these two links in the `Event` struct and then use those urls in `EventStore.ack_events` instead of constructing your own. That does introduce an issue with acking/nacking multiple events at the same time. Either you could make multiple requests, or (danger zone) start parsing the real event ID from the links and comma-join them.

Real life example response from `GET /subscription/:stream/:group` for a subscription with `resolveLinkTos` enabled:

``` json
{
  "title": "Messages for 'NotificationsWorkQueue/notifications-api'",
  "id": "http://master.billy.dev:2113/subscriptions/NotificationsWorkQueue/notifications-api",
  "updated": "2016-03-04T09:13:54.358156Z",
  "author": {
    "name": "EventStore"
  },
  "headOfStream": false,
  "links": [
    {
      "uri": "http://master.billy.dev:2113/subscriptions/NotificationsWorkQueue/notifications-api/ack?ids=006fb0c7-d30a-4618-9d69-2d0c396ab0df",
      "relation": "ackAll"
    },
    {
      "uri": "http://master.billy.dev:2113/subscriptions/NotificationsWorkQueue/notifications-api/nack?ids=006fb0c7-d30a-4618-9d69-2d0c396ab0df",
      "relation": "nackAll"
    },
    {
      "uri": "http://master.billy.dev:2113/subscriptions/NotificationsWorkQueue/notifications-api/1",
      "relation": "previous"
    },
    {
      "uri": "http://master.billy.dev:2113/subscriptions/NotificationsWorkQueue/notifications-api",
      "relation": "self"
    }
  ],
  "entries": [
    {
      "eventId": "d886a4c4-ea6b-422d-b96c-22e9bd31a133",
      "eventType": "QuoteSigned",
      "eventNumber": 0,
      "data": "{\n  \"id\": \"oQ6vaBSfQuacQqjJ5Gwebg\",\n  \"name\": \"yolo\",\n  \"email\": \"yolo@billy.dk\",\n  \"ip\": \"192.168.23.1\",\n  \"signatureUrl\": \"https://billysbilling-test-files-resource.s3.amazonaws.com/uploads/8dea5a4c-cd67-4bc5-a887-ac9587f68981/signature.png\"\n}",
      "metaData": "",
      "linkMetaData": "{\"$v\":\"5:-1:0:3\",\"$c\":194724408,\"$p\":194724408,\"$s\":{\"QuoteSigned\":-1,\"UserCommentedOnBill\":-1,\"UserCommentedOnContact\":-1,\"UserCommentedOnInvoice\":-1,\"UserCommentedOnSalesTaxReturn\":-1,\"UserCommentedOnTransaction\":-1},\"$causedBy\":\"d886a4c4-ea6b-422d-b96c-22e9bd31a133\"}",
      "streamId": "Invoice-oQ6vaBSfQuacQqjJ5Gwebg",
      "isJson": true,
      "isMetaData": false,
      "isLinkMetaData": true,
      "positionEventNumber": 0,
      "positionStreamId": "NotificationsWorkQueue",
      "title": "0@Invoice-oQ6vaBSfQuacQqjJ5Gwebg",
      "id": "http://master.billy.dev:2113/streams/Invoice-oQ6vaBSfQuacQqjJ5Gwebg/0",
      "updated": "2016-03-08T12:24:38.297449Z",
      "author": {
        "name": "EventStore"
      },
      "summary": "$>",
      "links": [
        {
          "uri": "http://master.billy.dev:2113/streams/Invoice-oQ6vaBSfQuacQqjJ5Gwebg/0",
          "relation": "edit"
        },
        {
          "uri": "http://master.billy.dev:2113/streams/Invoice-oQ6vaBSfQuacQqjJ5Gwebg/0",
          "relation": "alternate"
        },
        {
          "uri": "http://master.billy.dev:2113/subscriptions/NotificationsWorkQueue/notifications-api/ack/006fb0c7-d30a-4618-9d69-2d0c396ab0df",
          "relation": "ack"
        },
        {
          "uri": "http://master.billy.dev:2113/subscriptions/NotificationsWorkQueue/notifications-api/nack/006fb0c7-d30a-4618-9d69-2d0c396ab0df",
          "relation": "nack"
        }
      ]
    }
  ]
}
```

See how the `eventId` is `d886a4c4-ea6b-422d-b96c-22e9bd31a133`, but the `ack` link is ``http://master.billy.dev:2113/subscriptions/NotificationsWorkQueue/notifications-api/ack/006fb0c7-d30a-4618-9d69-2d0c396ab0df`.

**Comment by sebastianseilund** [comment]
Btw, nothing happens when you ack/nack an unknown event ID. This means that even if you try to ack your events, Event Store will never get notice of this, the event will be retried after `messageTimeoutMilliseconds` and be processed over and over again until `maxRetryCount` is hit.

**Comment by tudborg** [comment]
Damn you `noop` acks!
I'll take a look. Should be possible to get the actual event id, but otherwise the rels might be a solution.

**Comment by tudborg** [comment]
I made a dirty fix :(
Extracting the from the event links by assuming that the last segment of the uri is the id we need to ack on, in the ack relation.
That works, for now.

**Comment by tudborg** [comment]
0.1.1 released to hex with the above fixes

**Comment by tudborg** [comment]
On same note, do you have any suggestion on how to actually test that an ack'ed event is actually acked?

**Comment by sebastianseilund** [comment]
Hmm.. Only by controlling which events are pushed to a stream and then monitoring the `/subscriptions/:stream/:group/info` endpoint for `readBufferCount`, `totalInFlightMessages` and `retryBufferCount` to be `0`.
